[package]
name = "waypoint"
version = "0.5.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
inquire = { version = "0.7.5", features = ["editor"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
